# config.yaml
source_path: "D:\\Lakebridge_POC\\Source_Scripts"
target_path: "./Output_Scripts"
dialect: "Synapse"
profile: "lakebridge"
debug: false
run_validation: true
# new flags
run_analyzer: true
run_transpiler: true

